// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetsFoundation.Infraestructure.Persistance;

#nullable disable

namespace PetsFoundation.Migrations
{
    [DbContext(typeof(PetsContext))]
    [Migration("20250701235112_UpdateFirstNamePet")]
    partial class UpdateFirstNamePet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetsFoundation.Domain.AdoptionRequest", b =>
                {
                    b.Property<Guid>("KAdoptionRequest")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kAdoptionRequest");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<Guid>("KInterested")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kInterested");

                    b.Property<Guid>("KPet")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kPet");

                    b.Property<Guid>("KPetNavigationKPet")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KAdoptionRequest")
                        .HasName("PK__Adoption__F5B827EB4C37596D");

                    b.HasIndex("KInterested");

                    b.HasIndex("KPetNavigationKPet");

                    b.ToTable("AdoptionRequests");
                });

            modelBuilder.Entity("PetsFoundation.Domain.Interested", b =>
                {
                    b.Property<Guid>("KInterested")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kInterested");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdentificationType")
                        .HasColumnType("int");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("KInterested")
                        .HasName("PK__Interest__85479F705954CEA0");

                    b.ToTable("Interested", (string)null);
                });

            modelBuilder.Entity("PetsFoundation.Domain.Pet", b =>
                {
                    b.Property<Guid>("KPet")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kPet");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdentificationNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("KGodFather")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kGodFather");

                    b.Property<Guid?>("KOwner")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kOwner");

                    b.Property<int>("PetType")
                        .HasColumnType("int");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("KPet")
                        .HasName("PK__Pets__DFC35C4A79DFE013");

                    b.HasIndex("KGodFather");

                    b.HasIndex("KOwner");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetsFoundation.Domain.AdoptionRequest", b =>
                {
                    b.HasOne("PetsFoundation.Domain.Interested", "KInterestedNavigation")
                        .WithMany("AdoptionRequests")
                        .HasForeignKey("KInterested")
                        .IsRequired()
                        .HasConstraintName("FK__AdoptionR__kInte__4AB81AF0");

                    b.HasOne("PetsFoundation.Domain.Pet", "KPetNavigation")
                        .WithMany()
                        .HasForeignKey("KPetNavigationKPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KInterestedNavigation");

                    b.Navigation("KPetNavigation");
                });

            modelBuilder.Entity("PetsFoundation.Domain.Pet", b =>
                {
                    b.HasOne("PetsFoundation.Domain.Interested", "KGodFatherNavigation")
                        .WithMany("PetKGodFatherNavigations")
                        .HasForeignKey("KGodFather")
                        .HasConstraintName("FK__Pets__kGodFather__412EB0B6");

                    b.HasOne("PetsFoundation.Domain.Interested", "KOwnerNavigation")
                        .WithMany("PetKOwnerNavigations")
                        .HasForeignKey("KOwner")
                        .HasConstraintName("FK__Pets__kOwner__4222D4EF");

                    b.Navigation("KGodFatherNavigation");

                    b.Navigation("KOwnerNavigation");
                });

            modelBuilder.Entity("PetsFoundation.Domain.Interested", b =>
                {
                    b.Navigation("AdoptionRequests");

                    b.Navigation("PetKGodFatherNavigations");

                    b.Navigation("PetKOwnerNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
